### ISSUE TITLE
Use brightness sensor as alternative to proximity sensor

### ISSUE THREAD

**Issue by xela-zone** [lzanita09/NotificationPeekPort#1]
Segguet using the brightness sensor if proximity detector is not available.

**Comment by lzanita09** [comment]
Sorry I'm not very familiar with sensors in Android, do you mean [light sensor](http://developer.android.com/reference/android/hardware/Sensor.html#TYPE_LIGHT) ?

**Comment by xela-zone** [comment]
Yes, sorry.

**Comment by lzanita09** [comment]
OK. I'm not sure there is any device that runs KitKat that doesn't have proximity sensor...But I'll try, and perhaps lower the min sdk to Jelly Bean.

**Comment by xela-zone** [comment]
My nexus 7 2012 is on KK and does not have a proximity sensor. 

Perhaps the implementation could be like [flip cover control](https://play.google.com/store/apps/details?id=com.gbolger.covercontrol)

**Comment by lzanita09** [comment]
OK then, I'll try to make it work.
