### ISSUE TITLE
20140510: Clock and notification icons overlap.

### ISSUE THREAD

**Issue by ddantzler** [lzanita09/NotificationPeekPort#13]
See the overlap below. Please ignore volume controls. Clumsy fingers.

![screenshot_2014-05-10-12-22-24](https://cloud.githubusercontent.com/assets/1066466/2936515/ee4cd39c-d85f-11e3-9f84-2eb852992511.png)

**Comment by lzanita09** [comment]
Please try the latest build I just uploaded. The problem should be fixed.

**Comment by ddantzler** [comment]
This has been fixed.

**Comment by ddantzler** [comment]
Thanks!
