### ISSUE TITLE
Force close

### ISSUE THREAD

**Issue by Slugslinger** [lzanita09/NotificationPeekPort#2]
The app seams to force close if I leave any notification to be there for a while.

**Comment by lzanita09** [comment]
Do you know how to get stack trace from the log? That'll be very helpful for me to reproduce the FC.

**Comment by Slugslinger** [comment]
I'm not familiar, but I will try to understand and learn a way of doing it. And great job, this app is really helpful.

**Comment by Slugslinger** [comment]
Ok I think this was my mistake and sorry. For what I see in logcat it seams the event listeners are removed after the timeout decided in app right? I would like to know if its possible to remove this timeout?

**Comment by lzanita09** [comment]
Do you want them to listen all the time?

**Comment by Slugslinger** [comment]
Yes or would that be too much battery consuming? Maybe at least 2 minutes for example. Since now for what I see it's like 9 seconds and my cellphone is the Nexus 4 (vibration is weak) so when I see the notification light its too late.

**Comment by nasimdejai** [comment]
lzanita09, why is it (Active Display feature) not working for me on my nexus 5 running stock KitKat 4.4.2. Installed the latest apk and when I go to Settings-Display I can't find Peek Notification. Help pls

**Comment by lzanita09** [comment]
If you look closely, the video in Android Authority is actually from Paranoid Android, the rom modifies the system settings and adds Notification Peek option there. This app is a port version of just the feature, and you need to enable it in Device Administration and Notification Access to make it work.

Also if you want to uninstall the app, first deactivate it Device Administrator, then uninstall.

**Comment by Slugslinger** [comment]
Ok I was playing around and found that if I wake up the screen with the application and accidentally turn him, he tries to put the app in landscape and then force close, not sure if it happens only to me.
