### ISSUE TITLE
Wake screen if on the table

### ISSUE THREAD

**Issue by Wikiwix** [lzanita09/NotificationPeekPort#20]
On my Nexus 7 I have notification sounds disabled to be less intrusive, but it would be nice if there was an option to let the app show up once as a new notification arrives and the tablet lies on the table.
If you want this feature to be even smarter and more intuitive: activate it if  sound and vibration is off and deactivate it if sound and/or vibration is on

If you don't get something then feel free to ask

**Comment by lzanita09** [comment]
That sounds nice, combining sound and vibration configuration with notification display.

Currently it is possible to wake up screen if it is on table, just disable gyroscope sensor, and it'll only listen to proximity sensor.

**Comment by Wikiwix** [comment]
Yes, that's right but that way it is activated while in a pocket as well and it won't show up on taking device up/knocking hard. The "proximity" via light does not work that good...

By the way, what do you think of a REAL always listening function (i think this option is not described very well in the settings ( i will make a pullrequest for that string in a minute)

**Comment by lzanita09** [comment]
Disabling gyro sensor will disable the ability to wake up device on taking device up, the listener is not registered at that point. I have adjusted the proximity sensor a little bit today, but I haven't tested the light sensor, will do that later.

The REAL always listening you mean wake up screen even there is no notification?

**Comment by Wikiwix** [comment]
I do not know what you want to tell me with your first sentences... I just wanted to show reasons why my requested feature makes sense...

The last one: Yes, that's what I mean

**Comment by lzanita09** [comment]
Oh haha, what I mean is that if you disable gyro sensor, the app will not listen to position changes of the phone, therefore it cannot wake up the device when you hold it on your hand.

**Comment by Wikiwix** [comment]
Perhaps I was a bit unclear :D 
I know that it is that way(that is one of the reasons why I want a turn screen on on receive option), but I did not get what you wanted to tell me by that information...
