### ISSUE TITLE
20140514: Problems

### ISSUE THREAD

**Issue by ddantzler** [lzanita09/NotificationPeekPort#22]
Not sure how to describe them all. Seems to show Peek activity only on first notification received following reboot. Will not allow double tap to close. Must open notification. Subsequent notifications don't seem to make the activity start, but will wake lock phone. Rolling back to previous build.

**Comment by lzanita09** [comment]
Have you tried clear app data? It sounds like the app is corrupted.

**Comment by ddantzler** [comment]
Pfft. Yes, that was it.
