### ISSUE TITLE
Bug after swipe dismiss

### ISSUE THREAD

**Issue by asdfzz** [lzanita09/NotificationPeekPort#25]
Hi,
If i have 2 notifications (mail/hangout for example) i swiped away mail notif,then i tried open hangout one it will open mail message :)﻿

Video: http://it.tinypic.com/r/2zphw6r/8

**Comment by lzanita09** [comment]
I'm preparing a fix for that now, Deron and I are testing.

**Comment by asdfzz** [comment]
Closed :)
Tested all is ok :+1:
