### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by slave45** [lzanita09/NotificationPeekPort#3]
First, i can't see NotificationPeek in seetings/display as in your video clip.
I am not receiving any notification.
I try to uninstall but i can't remove.
Installed on S4 kitkat 4.4.2.
Can you please help me to remove this app.

**Comment by nasimdejai** [comment]
I also installed the same thing on my nexus 5 and can't seem to get it to work. Having same problem as you. Would like to uninstall it as well.

**Comment by slave45** [comment]
I just uninstall using ES File explorer(google play).Via this app,when you locate ap and try to uninstall,will ask you first to deactivate granted permission and after is easy to remove.
Standard application manager can't disable application(in info for app is not active at all, you can't use force stop) and that is reason for not uninstalling.

**Comment by nasimdejai** [comment]
slave45, thanks for the suggestion. It worked. I was able to uninstall it. Cheers

**Comment by lzanita09** [comment]
The reason why you can't uninstall the app is the device administrator forbid it (since you enable it in the app). To uninstall, go to your system settings, choose security, device administrator, and deactivate Notification Peek, and then uninstall.
