### ISSUE TITLE
Dismiss notifications

### ISSUE THREAD

**Issue by z-m-k** [lzanita09/NotificationPeekPort#8]
Can you dismiss notifications upon clicking on them from Peek?

**Comment by lzanita09** [comment]
Currently the only way to dismiss notification from Peek is to click the icon.

**Comment by z-m-k** [comment]
Then this is broken in the latest release. I did a test with Pushbullet and clicking the icon does not dismiss it.

**Comment by lzanita09** [comment]
Did it redirect you to the app?

**Comment by z-m-k** [comment]
Yes it did. It also does not dismiss its own test notification.

**Comment by lzanita09** [comment]
Sorry my bad, Peek is not responsible for notification dismiss, it only follows the PendingIntent in the original notification, which might or might not dismiss the notification. The app's own notification, for example, doesn't clear itself after clicking.

**Comment by z-m-k** [comment]
Hm. Makes sense. Closing.

But it would also be nice (I know it is not in the original Peek) to be able to dismiss any notification from Peek itself (w/o actually entering the app).

**Comment by lzanita09** [comment]
I'll try, thanks for letting me know.
